### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by FlipperPA** [pycontribs/activedirectory#1]
Good afternoon,

If you could provide some basic examples, such as connecting to an A.D. server and performing a simple LDAP query, I'd be happy to take the ball and run with it to start some documentation, starting with the README. Thanks for your efforts!

Regards,

-Tim
##

**Comment by cannatag** [comment]
Hello Tim,
I can give you examples on how to connect to LDAP servers, but I don't have
any experience with Active Directory! :(
Anyway I'm updating the manual and hope to have a more comprehensive online
documentation soon. I would be happy to include something on Active
Directory, but I have no direct access to it.

Bye,
Giovanni

2014-08-20 19:35 GMT+02:00 Timothy Allen notifications@github.com:

**Comment by ssbarnea** [comment]
There is no documentation yet but the unitests are as good as a documentation. Just try to run the activedirectory.py - this will run the unittests. After this you can look inside to see each function.

Doc will be added soon but it was not a priority yet, especially due to the fact that code is documented.

**Comment by ssbarnea** [comment]
Closing until someone wants to continue maintenance of this project. Just add a comment if you want.
